version: '3'

volumes:
  mongodb:
  
services:
    frontend:
        container_name: express_frontend
        restart: unless-stopped
        image: wkeplon/cvexpress_frontend:dev-cloud
        ports:
            - '7001:80'
    app:
        container_name: express_app
        restart: unless-stopped
        image: wkeplon/cvexpress_app:dev
        environment:
            - CORS_URL=https://mycv.atkev.site
            - MONGO_DB=mongodb://mongodb:27017/express
            - NODE_ENV=build
            - USERNAME_APP=admin
            - PASSWORD_APP=password
            - JWT_TOKEN_SECRET=itisasecretorisit
            - SALT_ROUNDS=10
        ports:
            - '7002:9000'
        depends_on:
            - db
    db:
        container_name: mongodb
        restart: unless-stopped
        image: mongo:4.4
        volumes: 
            - mongodb:/data/db
        expose:
            - '27017'
