version: '3'

volumes:
  mongodb:
  
services:
    app:
        container_name: express_app
        restart: unless-stopped
        build: ./
        ports:
            - '7000:7000'
    db:
        container_name: mongodb
        restart: unless-stopped
        image: mongo:4.4
        volumes: 
            - mongodb:/data/db
        ports:
            - '27017:27017'
