version: '3'

volumes:
  mongodb:
  
services:
    app:
        container_name: express_app
        restart: unless-stopped
        build: ./
        environment:
            - MONGO_DB=mongodb+srv://admin:password12345@express-lizue.mongodb.net/express?retryWrites=true&w=majority
            - NODE_ENV=development
            - USERNAME_APP=admin
            - PASSWORD_APP=password
            - JWT_TOKEN_SECRET=itisasecretorisit
            - SALT_ROUNDS=10
        ports:
            - '7001:9000'
    db:
        container_name: mongodb
        restart: unless-stopped
        image: mongo:4.4
        volumes: 
            - mongodb:/data/db
        ports:
            - '27017:27017'
