version: '3'

volumes:
  mongodb:
  
services:
    db:
        container_name: mongodb
        restart: unless-stopped
        image: mongo:4.4
        volumes: 
            - mongodb:/data/db
        ports:
            - '27017:27017'
